### ISSUE TITLE
Trained network parameters

### ISSUE THREAD

**Issue by ChiWeiHsiao** [Maryeon/asen#1]
Hi, thank you for sharing this great work!
I hope to run the model, but it seems that the trained weight is not released.
Would you consider releasing the trained network parameters to public? Thank you!

**Comment by Maryeon** [comment]
> Hi, thank you for sharing this great work!
> I hope to run the model, but it seems that the trained weight is not released.
> Would you consider releasing the trained network parameters to public? Thank you!
I have released a pretrained ASENet_V2 model which is trained on FashionAI dataset available at http://maryeon.com/file/checkpoint.tar.gz.

**Comment by ChiWeiHsiao** [comment]
That's great! Many thanks.
