### ISSUE TITLE
General queries 

### ISSUE THREAD

**Issue by ajay01994** [Maryeon/asen#7]
Dear @Maryeon 

Firstly thanks a lot for publishing the ASEN code , & a hearty congratulation for your paper publication your paper and model seems pretty robust and achieves a quite decent MAP score  on multiple fashion dataset, I am working on fine grain attribute prediction for fashion image classification and retrieval. I wish to use ASEN code as a part of research purpose for the mentioned tasks. I wish to understand the code in detail, I am facing issues with dataset availability. For Fashion AI and DARP, It  would be very kind of you if you could help me in giving some insights, help books, documentation  or code go through so that I could implement in Colab notebook. Or please  let me know if you have other mediums where I could reach out to you  .

Thanking you 

Ajay

**Comment by Maryeon** [comment]
@ajay01994 Hi, links to fetch FashionAI and DARN dataset can be found in README.md.

**Comment by ajay01994** [comment]
Ya i got it , Thanks :)
